language: go

services:
  - postgresql

install: make install

before_script:
  - curl -L https://packagecloud.io/mattes/migrate/gpgkey | apt-key add -
  - echo "deb https://packagecloud.io/mattes/migrate/ubuntu/ xenial main" > /etc/apt/sources.list.d/migrate.list
  - apt-get update
  - apt-get install -y migrate
  - psql -c 'create database ci_test;' -U postgres
  - migrate -database postgres://postgres@localhost:5432/ci_test -path sql up

script: make test