language: go

services:
  - postgresql

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update
  - sudo apt-get install -y glide

install: make install

before_script:
  - psql -c 'create database ci_test;' -U postgres

script: make test